### PR TITLE
docker file

### PR DESCRIPTION
**Pull request by reborg**
Added a Dockerfile. Some instructions on how to build are at the top (prerequisite is of course Docker installed and running). It looks like it works by connecting to `locahost:2021`, but `ncat localhost 50505` doesn't work here (no response) so it would be good to know if it's a local problem or not.

TODO:
* Allow to specify import dump to load on startup.

### CODE REVIEW

**Comment by reborg** [comment]
Some reasoning regarding seeding data into a dockerized Site. @armincerf and @malcolmsparks please have a look.

The current model to seed data requires a REPL connection. Considering the site process would be running in a Docker container, this is not very practical (you would need to know how to connect to the running image, which would be different at each restart and have the 50505 port accessible). We could think of exposing `import-resources` in other ways, for instance as some special HTTP endpoint that is installed at boot, hence the import of seed data could happen straight after Site comes up. We would POST to `/seed` some URL location of the seed data (file or otherwise) that Site can load and install.

Given the fact that this operation requires root privileges, it should only be allowed if there isn't a super user installed already. If the super user is already installed in Site, we should assume permissions or seed-data have already been established and a full import dump cannot happen.

**Comment by reborg** [comment]
> 
> So there is already a way to post .edn files into site, with the site cli (which you can look at in `./bin/site`). I think that should work and you don't need to worry about auth because that's already taken care of

True, missed it on a first glance. But we have this meta-circular problem of having to push seed data which includes root user auth and having to do that pending getting your token. I'm looking at how to go around this, but ideas welcome.

**Comment by armincerf** [comment]
> 
> 
> > 
> 
> > So there is already a way to post .edn files into site, with the site cli (which you can look at in `./bin/site`). I think that should work and you don't need to worry about auth because that's already taken care of
> 
> 
> 
> True, missed it on a first glance. But we have this meta-circular problem of having to push seed data which includes root user auth and having to do that pending getting your token. I'm looking at how to go around this, but ideas welcome.

Yeah good point, I guess there's a few options I can think of off the top of my head:

- have secret in an env var or something that can be used to setup a super user
- pre seed a super user with a default password and just make it a required step to change that password before anything else can be inserted 
- find a way to ssh into the container for the setup and then lock the door afterwards

**Comment by reborg** [comment]
@armincerf I think I solved the problem of importing resources. This is not happening here, it's a responsibility of the inheriting project, so this Docker image is ready for merging. It is just adding the Docker file to the project and people can use it to build local site instances. Any other setup steps can happen as normal.

**Review by armincerf — APPROVED** [review]

**Pull request merged**
